In [1]:
# connect to the sql server from the notebook
import pandas as pd
import pyodbc

In [2]:
# connect to the database
connector = pyodbc.connect(
    'DRIVER={ODBC Driver 17 for SQL Server};'
    'SERVER=LAPPY\\SQLEXPRESS;'
    'DATABASE=DunnhumbyDB;'
    'Trusted_Connection=yes;'
)

In [3]:
# load a sample of transaction data into a Data Frame
query_transactions = "SELECT TOP 1000 * FROM silver.transaction_data"
df_transactions = pd.read_sql(query_transactions, connector)
df_transactions.head()

C:\Users\bhawa\AppData\Local\Temp\ipykernel_26208\3077572258.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_transactions = pd.read_sql(query_transactions, connector)

,household_key,basket_id,day,product_id,quantity,sales_value,store_id,retail_disc,trans_time,week_no,coupon_disc,coupon_match_disc,dwh_create_date
0,1795,33460582829,441,834103,1,0.50,31782,-0.79,2345,64,0.0,0.0,2026-08-02 12:29:06.550
1,1795,33460582829,441,921432,0,0.00,31782,0.00,2345,64,0.0,0.0,2026-08-02 12:29:06.550
2,1795,33460582829,441,949616,1,0.34,31782,-0.26,2345,64,0.0,0.0,2026-08-02 12:29:06.550
3,1795,33460582829,441,1069175,0,0.00,31782,0.00,2345,64,0.0,0.0,2026-08-02 12:29:06.550
4,1289,33460582864,442,1095011,1,2.59,31782,0.00,36,64,0.0,0.0,2026-08-02 12:29:06.550

In [4]:
# get to know this Data Frame
df_transactions.shape

(1000, 13)

In [5]:
# displays each column's name, non-null value count, and data type.
df_transactions.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   household_key      1000 non-null   int64
 1   basket_id          1000 non-null   int64
 2   day                1000 non-null   int64
 3   product_id         1000 non-null   int64
 4   quantity           1000 non-null   int64
 5   sales_value        1000 non-null   float64
 6   store_id           1000 non-null   int64
 7   retail_disc        1000 non-null   float64
 8   trans_time         1000 non-null   int64
 9   week_no            1000 non-null   int64
 10  coupon_disc        1000 non-null   float64
 11  coupon_match_disc  1000 non-null   float64
 12  dwh_create_date    1000 non-null   datetime64[us]
dtypes: datetime64[us](1), float64(4), int64(8)
memory usage: 101.7 KB

In [6]:
# load the product table
query_product = "SELECT product_id, department, commodity_desc, sub_commodity_desc FROM silver.product"
df_product = pd.read_sql(query_product, connector)
df_product.head()

C:\Users\bhawa\AppData\Local\Temp\ipykernel_26208\1199290581.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_product = pd.read_sql(query_product, connector)

,product_id,department,commodity_desc,sub_commodity_desc
0,25671,GROCERY,FRZN ICE,ICE - CRUSHED/CUBED
1,26081,MISC. TRANS.,NO COMMODITY DESCRIPTION,NO SUBCOMMODITY DESCRIPTION
2,26093,PASTRY,BREAD,BREAD:ITALIAN/FRENCH
3,26190,GROCERY,FRUIT - SHELF STABLE,APPLE SAUCE
4,26355,GROCERY,COOKIES/CONES,SPECIALTY COOKIES

In [7]:
# join transactions with product infomation
df_transactions = df_transactions.merge(df_product, on = 'product_id', how = 'left')
df_transactions.head()

,household_key,basket_id,day,product_id,quantity,sales_value,store_id,retail_disc,trans_time,week_no,coupon_disc,coupon_match_disc,dwh_create_date,department,commodity_desc,sub_commodity_desc
0,1795,33460582829,441,834103,1,0.50,31782,-0.79,2345,64,0.0,0.0,2026-08-02 12:29:06.550,GROCERY,SOFT DRINKS,SFT DRNK SNGL SRV BTL CARB (EX
1,1795,33460582829,441,921432,0,0.00,31782,0.00,2345,64,0.0,0.0,2026-08-02 12:29:06.550,GROCERY,SOFT DRINKS,MIXERS(TONIC WTR/GNGR ALE)FLAV
2,1795,33460582829,441,949616,1,0.34,31782,-0.26,2345,64,0.0,0.0,2026-08-02 12:29:06.550,DRUG GM,CANDY - CHECKLANE,CANDY BARS (SINGLES)(INCLUDING
3,1795,33460582829,441,1069175,0,0.00,31782,0.00,2345,64,0.0,0.0,2026-08-02 12:29:06.550,GROCERY,SOFT DRINKS,SOFT DRINK BOTTLE NON-CARB (EX
4,1289,33460582864,442,1095011,1,2.59,31782,0.00,36,64,0.0,0.0,2026-08-02 12:29:06.550,GROCERY,COOKIES/CONES,VANILLA WAFER/KIDS COOKIES

In [8]:
# check the join actually worked
df_transactions['commodity_desc'].isnull().sum()

np.int64(0)

In [9]:
# load campaign tables
df_campaign_table = pd.read_sql("SELECT household_key, campaign FROM silver.campaign_table", connector)
df_campaign_desc = pd.read_sql("SELECT campaign, start_day, end_day FROM silver.campaign_desc", connector)

C:\Users\bhawa\AppData\Local\Temp\ipykernel_26208\709763586.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_campaign_table = pd.read_sql("SELECT household_key, campaign FROM silver.campaign_table", connector)
C:\Users\bhawa\AppData\Local\Temp\ipykernel_26208\709763586.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_campaign_desc = pd.read_sql("SELECT campaign, start_day, end_day FROM silver.campaign_desc", connector)

In [10]:
# combine them into one exposure window table
df_exposure = df_campaign_table.merge(df_campaign_desc, on = 'campaign', how = 'left')
df_exposure.head()

   household_key  campaign  start_day  end_day
0              1         8        412      460
1              1        13        504      551
2              1        18        587      642
3              2        18        587      642
4              3         8        412      460

In [11]:
# pick one household to test with
test_household = df_exposure['household_key'].iloc[0]
test_household

np.int64(1)

In [12]:
# Look at that household's transactions and campaign windows side by side
sample_transactions = df_transactions[df_transactions['household_key'] == test_household] [['household_key', 'day', 'commodity_desc', 'sales_value']]
sample_exposure = df_exposure[df_exposure['household_key'] == test_household]
print(sample_transactions.head(10))
print(sample_exposure)

Empty DataFrame
Columns: [household_key, day, commodity_desc, sales_value]
Index: []
      household_key  campaign  start_day  end_day
0                 1         8        412      460
1                 1        13        504      551
2                 1        18        587      642
3979              1        12        477      509
3980              1        22        624      656
3981              1        23        646      684
3982              1        29        281      334
6634              1        20        615      685

In [13]:
# Observation: We loaded only the first 1000 transaction records, so a household selected from the full campaign
# dataset may not exist in this sample, resulting in an empty DataFrame. To avoid this, we now select
# the test household from df_transactions instead of df_exposure, ensuring it has transaction records.

In [14]:
# pick a household that actually has transactions in our sample
test_household = df_transactions['household_key'].iloc[0]
test_household

np.int64(1795)

In [15]:
# rerun the comparision with this corrected household
sample_transactions = df_transactions[df_transactions['household_key'] == test_household] [['household_key', 'day', 'commodity_desc', 'sales_value']]
sample_exposure = df_exposure[df_exposure['household_key'] == test_household]
print(sample_transactions.head(10))
print(sample_exposure)

   household_key  day     commodity_desc  sales_value
0           1795  441        SOFT DRINKS         0.50
1           1795  441        SOFT DRINKS         0.00
2           1795  441  CANDY - CHECKLANE         0.34
3           1795  441        SOFT DRINKS         0.00
      household_key  campaign  start_day  end_day
2816           1795         8        412      460
2817           1795        13        504      551
2818           1795        18        587      642
5797           1795        11        477      523
5798           1795        17        575      607
5799           1795        22        624      656
5800           1795        25        659      691
5801           1795        29        281      334

In [16]:
# Observation: Transactions for the selected household occur on day 1, while its campaign windows start 
# much later (days 504–551 and 587–642). Since none of the transactions fall within a campaign period, all
# observed purchases represent baseline (pre-campaign) spending.

In [17]:
# define a function to check "was this day during any campaign"
def is_during_campaign(day, exposure_df):
    matches = exposure_df[(exposure_df['start_day'] <= day) & (exposure_df['end_day'] >= day)]
    return not matches.empty

In [18]:
# apply this function to our sample transaction
sample_transactions['during_campaign'] = sample_transactions['day'].apply(lambda d: is_during_campaign(d, sample_exposure))
sample_transactions

   household_key  day     commodity_desc  sales_value  during_campaign
0           1795  441        SOFT DRINKS         0.50             True
1           1795  441        SOFT DRINKS         0.00             True
2           1795  441  CANDY - CHECKLANE         0.34             True
3           1795  441        SOFT DRINKS         0.00             True

In [19]:
# apply this to every transaction in df_transaction (not just the test_household)
df_transactions['during_campaign'] = df_transactions.apply(lambda row: is_during_campaign(row['day'], df_exposure[df_exposure['household_key'] == row['household_key']]),
                                                        axis = 1)
df_transactions['during_campaign'].value_counts()

during_campaign
True     622
False    378
Name: count, dtype: int64

In [20]:
# Diagnosed data filtering issue and strategized sampling refinement:
# Observation: All transactions are marked False because the TOP 1000 sample contains only early transaction days,
# before any campaigns begin. The campaign-matching logic is correct; the issue lies in the sampling method.

In [21]:
# pull a sample that's actually likely to include campaign exposed transactions
query_targeted = """SELECT TOP 2000 t.*
                    FROM silver.transaction_data AS t
                    INNER JOIN silver.campaign_table AS c
                    ON t.household_key = c.household_key
                    ORDER BY t.household_key"""
df_transactions = pd.read_sql(query_targeted, connector)
df_transactions.shape

C:\Users\bhawa\AppData\Local\Temp\ipykernel_26208\3009683294.py:7: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_transactions = pd.read_sql(query_targeted, connector)

(2000, 13)

In [22]:
# redo the category join and campaign-window check on this new sample
df_transactions = df_transactions.merge(df_product, on = 'product_id', how = 'left')
df_transactions['during_camapign'] = df_transactions.apply(lambda row: is_during_campaign(row['day'], df_exposure[df_exposure['household_key'] == row['household_key']]),
                                                           axis = 1)
df_transactions['during_camapign'].value_counts()

during_camapign
False    1106
True      894
Name: count, dtype: int64

In [23]:
# calculate baseline spend per household per category
baseline_spend = df_transactions[df_transactions['during_camapign'] == False].groupby(['household_key', 'commodity_desc'])['sales_value'].sum().reset_index()
baseline_spend = baseline_spend.rename(columns = {'sales_value' : 'baseline_spend'})
baseline_spend.head()

   household_key commodity_desc  baseline_spend
0              1                           0.00
1              1       AIR CARE           42.16
2              1     ANALGESICS           10.68
3              1         APPLES           15.58
4              1          BACON            5.00

In [24]:
# calculate the campaign exposed spend the same way
campaign_spend = df_transactions[df_transactions['during_camapign'] == True].groupby(['household_key', 'commodity_desc'])['sales_value'].sum().reset_index()
campaign_spend = campaign_spend.rename(columns = {'sales_value' : 'campaign_spend'})
campaign_spend.head()

   household_key commodity_desc  campaign_spend
0              1                           0.00
1              1       AIR CARE           27.47
2              1     ANALGESICS            5.99
3              1         APPLES           12.89
4              1          BACON           10.08

In [25]:
# merge baseline and campaign spend side by side
lift_df = baseline_spend.merge(campaign_spend, on = ['household_key', 'commodity_desc'], how = 'outer')
lift_df.head()

   household_key commodity_desc  baseline_spend  campaign_spend
0              1                           0.00            0.00
1              1       AIR CARE           42.16           27.47
2              1     ANALGESICS           10.68            5.99
3              1         APPLES           15.58           12.89
4              1          BACON            5.00           10.08

In [26]:
# fill in the gaps and calculate lift
lift_df['baseline_spend'] = lift_df['baseline_spend'].fillna(0)
lift_df['campaign_spend'] = lift_df['campaign_spend'].fillna(0)
lift_df['lift'] = lift_df['campaign_spend'] - lift_df['baseline_spend']
lift_df.sort_values('lift', ascending = False).head(10)

,household_key,commodity_desc,baseline_spend,campaign_spend,lift
23,1,CHEESES,44.26,75.32,31.06
74,1,IN-STORE PHOTOFINISHING,0.00,24.68,24.68
100,1,RICE CAKES,20.14,39.65,19.51
19,1,CANDY - PACKAGED,124.84,142.91,18.07
16,1,CAKES,10.97,25.94,14.97
37,1,CRACKERS/MISC BKD FD,47.72,62.60,14.88
84,1,MOLASSES/SYRUP/PANCAKE MIXS,0.00,12.26,12.26
110,1,SNACKS,0.00,10.27,10.27
95,1,POTATOES,11.74,20.94,9.20
67,1,HEAT/SERVE,73.35,82.42,9.07

In [27]:
# Identified two issues affecting the analysis.
# Observation: First, the TOP 2000 sample contains transactions from only household 1 due to the ORDER BY clause,
# resulting in a non-representative sample. Second, comparing raw baseline and campaign spend totals
# is misleading because they may cover different time periods, making lift calculations potentially biased.

In [28]:
# Lets check both
print(f'Number of unique households in transactions: {df_transactions['household_key'].nunique()}')
print(f'\nCampaign duration (days): {df_exposure['end_day'] - df_exposure['start_day']}')

Number of unique households in transactions: 1

Campaign duration (days): 0       48
1       47
2       55
3       55
4       48
        ..
7203    65
7204    70
7205    65
7206    32
7207    70
Length: 7208, dtype: int64

In [29]:
# Reconsider sample scope and normalized metrics for equitable analysis
# Observation: Verified that the current sample contains transactions from only one household due to the
# TOP 2000 + ORDER BY query. Also confirmed that campaign windows vary between 30–70 days,
# making raw baseline and campaign spend totals incomparable without normalizing for time.

In [30]:
# pull a real spread of households
query_targeted = """SELECT TOP 20000 t.*
                    FROM silver.transaction_data AS t
                    WHERE t.household_key IN(
                                             SELECT DISTINCT TOP 20 household_key
                                             FROM silver.campaign_table)"""
df_transactions = pd.read_sql(query_targeted, connector)
df_transactions['household_key'].nunique()

C:\Users\bhawa\AppData\Local\Temp\ipykernel_26208\2714612312.py:7: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_transactions = pd.read_sql(query_targeted, connector)

20

In [31]:
# check how many total days our data actually spans
df_transactions['day'].max() - df_transactions['day'].min()

np.int64(617)

In [32]:
# redo category join + campaign-window flag on new sample
df_transactions = df_transactions.merge(df_product, on = 'product_id', how = 'left')
df_transactions['during_campaign'] = df_transactions.apply(lambda row: is_during_campaign(row['day'], df_exposure[df_exposure['household_key'] == row['household_key']]),
                                                           axis = 1)
df_transactions['during_campaign'].value_counts()

during_campaign
False    13138
True      6862
Name: count, dtype: int64

In [33]:
# count campaign days vs baseline days per household
days_per_household = df_transactions.groupby(['household_key', 'during_campaign'])['day'].nunique().reset_index()
days_per_household = days_per_household.rename(columns = {'day' : 'num_days'})
days_per_household.head(10)

   household_key  during_campaign  num_days
0              1            False        30
1              1             True        25
2              2            False        35
3              2             True         3
4              3            False        31
5              3             True         4
6              4            False        22
7              6            False       109
8              6             True        41
9              7            False        24

In [34]:
# recalculate baseline and camapign spend on this new smaple
baseline_spend = df_transactions[df_transactions['during_campaign'] == False].groupby(['household_key', 'commodity_desc'])['sales_value'].sum().reset_index()
baseline_spend = baseline_spend.rename(columns={'sales_value': 'baseline_spend'})

campaign_spend = df_transactions[df_transactions['during_campaign'] == True].groupby(['household_key', 'commodity_desc'])['sales_value'].sum().reset_index()
campaign_spend = campaign_spend.rename(columns={'sales_value': 'campaign_spend'})

In [35]:
baseline_days = days_per_household[days_per_household['during_campaign'] == False][['household_key', 'num_days']].rename(columns={'num_days': 'baseline_days'})
campaign_days = days_per_household[days_per_household['during_campaign'] == True][['household_key', 'num_days']].rename(columns={'num_days': 'campaign_days'})

baseline_spend = baseline_spend.merge(baseline_days, on='household_key', how='left')
campaign_spend = campaign_spend.merge(campaign_days, on='household_key', how='left')

baseline_spend.head()

   household_key commodity_desc  baseline_spend  baseline_days
0              1                           0.00             30
1              1       AIR CARE           19.97             30
2              1     ANALGESICS            3.99             30
3              1         APPLES            7.31             30
4              1          BACON            2.50             30

In [36]:
# calculate spend per day for both baseline and camapign
baseline_spend['baseline_spend_per_day'] = baseline_spend['baseline_spend'] / baseline_spend['baseline_days']
campaign_spend['campaign_spend_per_day'] = campaign_spend['campaign_spend'] / campaign_spend['campaign_days']

baseline_spend.head()

,household_key,commodity_desc,baseline_spend,baseline_days,baseline_spend_per_day
0,1,,0.00,30,0.000000
1,1,AIR CARE,19.97,30,0.665667
2,1,ANALGESICS,3.99,30,0.133000
3,1,APPLES,7.31,30,0.243667
4,1,BACON,2.50,30,0.083333

In [37]:
# merge both per day rates together and compute the real lift
lift_df = baseline_spend.merge(campaign_spend, on=['household_key', 'commodity_desc'], how='outer')

lift_df['baseline_spend_per_day'] = lift_df['baseline_spend_per_day'].fillna(0)
lift_df['campaign_spend_per_day'] = lift_df['campaign_spend_per_day'].fillna(0)

lift_df['lift_per_day'] = lift_df['campaign_spend_per_day'] - lift_df['baseline_spend_per_day']

lift_df.sort_values('lift_per_day', ascending=False).head(10)

,household_key,commodity_desc,baseline_spend,baseline_days,baseline_spend_per_day,campaign_spend,campaign_days,campaign_spend_per_day,lift_per_day
1117,16,COUPON/MISC ITEMS,140.85,60.0,2.347500,24.20,1.0,24.200000,21.852500
1968,25,CIGARETTES,399.92,44.0,9.089091,269.06,15.0,17.937333,8.848242
1296,17,TURKEY,11.39,56.0,0.203393,108.41,25.0,4.336400,4.133007
130,2,BATH TISSUES,15.48,35.0,0.442286,13.49,3.0,4.496667,4.054381
876,13,COUPON/MISC ITEMS,1961.80,91.0,21.558242,1091.87,44.0,24.815227,3.256986
119,2,ANALGESICS,NaN,NaN,0.000000,8.99,3.0,2.996667,2.996667
2049,26,BACON,29.76,77.0,0.386494,10.00,3.0,3.333333,2.946840
1197,17,BEEF,194.35,56.0,3.470536,146.94,25.0,5.877600,2.407064
2159,27,BEERS/ALES,342.01,96.0,3.562604,764.51,131.0,5.835954,2.273350
202,2,LUNCHMEAT,1.99,35.0,0.056857,6.99,3.0,2.330000,2.273143

In [38]:
# Identified data quality issues and flagged inconsistent handling across columns
# Observation: The normalized per-day metrics are more meaningful, but very small campaign periods (e.g., 1 day)
# can produce misleadingly high spend rates. Additionally, missing baseline values are handled
# inconsistently —per-day metrics are filled with 0, while the corresponding raw spend and day
# columns still contain NaN, making the results potentially misleading.

In [39]:
# fix the NaN inconsistency first
lift_df['baseline_spend'] = lift_df['baseline_spend'].fillna(0)
lift_df['baseline_days'] = lift_df['baseline_days'].fillna(0)
lift_df['campaign_spend'] = lift_df['campaign_spend'].fillna(0)
lift_df['campaign_days'] = lift_df['campaign_days'].fillna(0)
lift_df.loc[1298]

household_key                                    17
commodity_desc            VEGETABLES - SHELF STABLE
baseline_spend                                  0.6
baseline_days                                  56.0
baseline_spend_per_day                     0.010714
campaign_spend                                  0.0
campaign_days                                   0.0
campaign_spend_per_day                          0.0
lift_per_day                              -0.010714
Name: 1298, dtype: object

In [40]:
# see how common the tiny denominator problem actually is
lift_df['campaign_days'].value_counts().sort_index().head(10)

campaign_days
0.0     996
1.0       1
3.0      46
4.0      40
9.0      72
15.0     59
16.0     47
19.0     42
21.0     87
22.0     51
Name: count, dtype: int64

In [41]:
# apply the minimum day threshold
MIN_DAYS = 5

reliable_lift = lift_df[(lift_df['baseline_days'] >= MIN_DAYS) & (lift_df['campaign_days'] >= MIN_DAYS)]
reliable_lift.shape

(1022, 9)

In [42]:
# look at the top reliable lifts
reliable_lift.sort_values('lift_per_day', ascending=False).head(10)

,household_key,commodity_desc,baseline_spend,baseline_days,baseline_spend_per_day,campaign_spend,campaign_days,campaign_spend_per_day,lift_per_day
1968,25,CIGARETTES,399.92,44.0,9.089091,269.06,15.0,17.937333,8.848242
1296,17,TURKEY,11.39,56.0,0.203393,108.41,25.0,4.336400,4.133007
876,13,COUPON/MISC ITEMS,1961.80,91.0,21.558242,1091.87,44.0,24.815227,3.256986
1197,17,BEEF,194.35,56.0,3.470536,146.94,25.0,5.877600,2.407064
2159,27,BEERS/ALES,342.01,96.0,3.562604,764.51,131.0,5.835954,2.273350
1335,18,COUPON/MISC ITEMS,295.89,59.0,5.015085,152.15,21.0,7.245238,2.230153
1221,17,DINNER SAUSAGE,17.96,56.0,0.320714,59.42,25.0,2.376800,2.056086
458,6,COUPON/MISC ITEMS,136.20,109.0,1.249541,120.64,41.0,2.942439,1.692898
2280,28,FROZEN PIZZA,70.11,61.0,1.149344,60.24,22.0,2.738182,1.588838
578,7,CHEESE,14.20,24.0,0.591667,19.22,9.0,2.135556,1.543889

In [43]:
# also check the bottom (negative lift) as a sanity check
reliable_lift.sort_values('lift_per_day', ascending=True).head(10)

,household_key,commodity_desc,baseline_spend,baseline_days,baseline_spend_per_day,campaign_spend,campaign_days,campaign_spend_per_day,lift_per_day
427,6,BEEF,432.97,109.0,3.972202,21.36,41.0,0.520976,-3.451226
722,8,COUPON/MISC ITEMS,123.94,38.0,3.261579,21.58,32.0,0.674375,-2.587204
1218,17,COUPON/MISC ITEMS,447.73,56.0,7.995179,139.00,25.0,5.560000,-2.435179
1867,23,DOMESTIC WINE,179.81,54.0,3.329815,18.98,16.0,1.186250,-2.143565
558,7,BABY FOODS,76.27,24.0,3.177917,9.61,9.0,1.067778,-2.110139
1713,22,BEEF,216.59,51.0,4.246863,76.54,31.0,2.469032,-1.777830
1284,17,SMOKED MEATS,228.03,56.0,4.071964,58.36,25.0,2.334400,-1.737564
103,1,SOFT DRINKS,89.70,30.0,2.990000,33.46,25.0,1.338400,-1.651600
37,1,DELI MEATS,61.07,30.0,2.035667,11.41,25.0,0.456400,-1.579267
1016,14,COUPON/MISC ITEMS,135.00,41.0,3.292683,35.00,19.0,1.842105,-1.450578

In [44]:
print(f"Total pairs: {len(lift_df)}, Reliable pairs: {len(reliable_lift)}, Dropped (unreliable): {len(lift_df) - len(reliable_lift)}")

Total pairs: 2333, Reliable pairs: 1022, Dropped (unreliable): 1311

In [45]:
# Key takeaways:
# • Promotional lift results are realistic, with expected increases (e.g., Cakes, Chicken,
#   Soft Drinks) and decreases (e.g., Beef, Frozen Pizza) reflecting genuine buying behavior.
# • Comparing per-day spend rates provides a fairer measure of campaign impact than raw spend totals.
# • Applying a minimum-days threshold removes unreliable household-category pairs and significantly
#   improves the reliability of the analysis.
# • Some catch-all categories (e.g., COUPON/MISC ITEMS) should be reviewed or excluded before
#   reporting, as they may not represent actual product purchasing behavior.
#
# Overall, the complete analysis workflow—from identifying campaign exposure, calculating baseline
# and campaign spend per day, normalizing for time, and filtering unreliable comparisons—has been
# validated and is ready to be implemented on the full dataset using SQL.